name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'IaaC/**.tf'
  pull_request:
    paths:
      - 'IaaC/**.tf'

jobs:
  terraform_plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Terraform Init
      run: terraform init
      working-directory: ./IaaC

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./IaaC
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  terraform_apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Terraform Init
      run: terraform init
      working-directory: ./IaaC

    - name: Terraform Apply
      run: terraform apply -auto-approve --refresh=true
      working-directory: ./IaaC
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
